# spec/kong_tests.conf
# Kong-Rust test configuration — Kong-Rust 测试配置

database = postgres
pg_host = 127.0.0.1
pg_port = 5432
pg_user = kong
pg_password = kong
pg_database = kong_tests

proxy_listen = 0.0.0.0:9000, 0.0.0.0:9443 ssl
admin_listen = 0.0.0.0:9001

log_level = info
