use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::common::{ForeignKey, PluginOrdering, Protocol};
use crate::traits::Entity;

/// Plugin entity — fully consistent with Kong plugins table — Plugin 实体 — 与 Kong plugins 表完全一致
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Plugin {
    pub id: Uuid,
    /// Plugin name, required — 插件名称，必填
    pub name: String,
    /// Plugin instance name — 插件实例名称
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance_name: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    /// Associated Route (optional, cascade delete) — 关联的 Route（可选，级联删除）
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route: Option<ForeignKey>,
    /// Associated Service (optional, cascade delete) — 关联的 Service（可选，级联删除）
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service: Option<ForeignKey>,
    /// Associated Consumer (optional, cascade delete) — 关联的 Consumer（可选，级联删除）
    #[serde(skip_serializing_if = "Option::is_none")]
    pub consumer: Option<ForeignKey>,
    /// Plugin configuration (dynamic JSON structure, defined by each plugin's schema) — 插件配置（动态 JSON 结构，由各插件 schema 定义）
    pub config: serde_json::Value,
    /// Protocols the plugin applies to — 插件适用的协议
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protocols: Option<Vec<Protocol>>,
    /// Cache key (auto-generated by Kong, uniquely identifies the plugin configuration) — 缓存键（由 Kong 自动生成，用于唯一标识插件配置）
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_key: Option<String>,
    /// Whether enabled, default true — 是否启用，默认 true
    pub enabled: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Plugin ordering configuration — 插件排序配置
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ordering: Option<PluginOrdering>,
    /// Workspace ID (foreign key to workspaces) — 工作空间 ID（外键引用 workspaces）
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ws_id: Option<Uuid>,
}

impl Default for Plugin {
    fn default() -> Self {
        Self {
            id: Uuid::new_v4(),
            name: String::new(),
            instance_name: None,
            created_at: 0,
            updated_at: 0,
            route: None,
            service: None,
            consumer: None,
            config: serde_json::Value::Object(serde_json::Map::new()),
            protocols: None,
            cache_key: None,
            enabled: true,
            tags: None,
            ordering: None,
            ws_id: None,
        }
    }
}

impl Entity for Plugin {
    fn table_name() -> &'static str {
        "plugins"
    }

    fn id(&self) -> Uuid {
        self.id
    }

    fn endpoint_key() -> Option<&'static str> {
        Some("instance_name")
    }

    fn endpoint_key_value(&self) -> Option<String> {
        self.instance_name.clone()
    }

    fn tags(&self) -> Option<&Vec<String>> {
        self.tags.as_ref()
    }
}
